name: Welcome
main: ru.nukkit.welcome.Welcome
version: "0.0.5"
author: fromgate, nukkit.ru
api: ["1.0.0"]
softdepend: [DbLib]
description: User authentication plugin
permissions:
  welcome.login:
    descripition: Allows to use commands /login and /logoff
    default: true
  welcome.register:
    description: Allows to use command /register
    default: true
  welcome.changepassword:
    description: Allows to use command /changepassword
    default: true
  welcome.help:
    description: Allows to use command /welcome help
    default: op
  welcome.remove:
    description: Allows to use command /welcome remove
    default: op
  welcome.unregister:
    description: Allows to use command /unregister
    default: op